"""Descripción de los cambios

Revision ID: c6968569353e
Revises: 35e906734c3e
Create Date: 2024-06-15 17:20:16.842199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6968569353e'
down_revision: Union[str, None] = '35e906734c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_moneda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('moneda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moneda_id'], ['moneda.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_moneda')
    # ### end Alembic commands ###
